//! Real-world-style search quality battery.
//!
//! Methodology from codegraph's `SEARCH_QUALITY_LOOP.md`: a fixed corpus of
//! real-world-shaped Kotlin (OkHttp/Okio-style networking + a protobuf stub +
//! a UI screen) and a fixed query battery asserting top-N hits. The corpus is
//! parsed through the real `parse_by_extension` path and indexed with the same
//! `doc_tokens`/`TfIdfIndex`/`parse_query` code `run_search` uses, so these
//! tests guard P1 (segmentation), P2 (filters), P3 (phantom suppression keeps
//! the corpus parse clean) and P4 (generated down-ranking) together.

use super::{doc_passes_filters, doc_tokens, language_from_path, parse_query, TfIdfIndex};
use crate::indexer::detect_generated;
use crate::parser::parse_by_extension;

/// Corpus entries are parsed as standalone files; `path` feeds the
/// generated-detection signal and the language filter.
struct CorpusEntry {
    path: &'static str,
    src: &'static str,
}

fn corpus() -> Vec<CorpusEntry> {
    vec![
        // OkHttp-style networking (hand-written).
        CorpusEntry {
            path: "okhttp/src/main/kotlin/okhttp3/Request.kt",
            src: r#"
package okhttp3

/**
 * An immutable HTTP request.
 */
class Request {
    fun newBuilder(): Builder = Builder()
}

class Builder {
    fun url(url: String): Builder = this
    fun build(): Request = Request()
}
"#,
        },
        // Okio-style buffered source (hand-written, KDoc-heavy).
        CorpusEntry {
            path: "okio/src/main/kotlin/okio/Buffer.kt",
            src: r#"
package okio

/**
 * A sink that buffers written bytes in memory, ready to be read as a source.
 */
class Buffer {
    fun writeUtf8(string: String): Buffer = this
    fun readUtf8(): String = ""
}
"#,
        },
        // Protobuf-generated stub with the same class name as a real one.
        CorpusEntry {
            path: "proto/Request.pb.kt",
            src: r#"
// Code generated by the protocol buffer compiler. DO NOT EDIT!
package okhttp3

class Request {
    fun parseFrom(bytes: ByteArray): Request = this
}
"#,
        },
        // Acronym-run class names (P1 segmentation).
        CorpusEntry {
            path: "html/src/main/kotlin/com/example/HTMLParser.kt",
            src: r#"
package com.example

class HTMLParser {
    fun parse(html: String): String = html
}
"#,
        },
        CorpusEntry {
            path: "json/src/main/kotlin/com/example/JSONParser.kt",
            src: r#"
package com.example

class JSONParser {
    fun parse(json: String): String = json
}
"#,
        },
        // Digits glued to a word (P1).
        CorpusEntry {
            path: "codec/src/main/kotlin/com/example/Base64Encoder.kt",
            src: r#"
package com.example

class Base64Encoder {
    fun encode(bytes: ByteArray): String = ""
}
"#,
        },
        // UI screen with camelCase method.
        CorpusEntry {
            path: "app/src/main/kotlin/com/example/LoginViewModel.kt",
            src: r#"
package com.example

class LoginViewModel {
    fun onLoginClicked() {}
}
"#,
        },
    ]
}

/// Build the same index `run_search` would, from parsed corpus files.
fn build_corpus_index() -> (TfIdfIndex, Vec<(String, String)>) {
    let mut tfidf = TfIdfIndex::new();
    // (name, kind) per doc, in index order — for top-N assertions.
    let mut names: Vec<(String, String)> = Vec::new();
    for entry in corpus() {
        let data = parse_by_extension(entry.path, entry.src);
        assert!(
            data.syntax_errors.is_empty(),
            "corpus file {} must parse clean (P3 phantom regression): {:?}",
            entry.path,
            data.syntax_errors
        );
        let generated = detect_generated(entry.path, entry.src);
        for sym in &data.symbols {
            let tokens = doc_tokens(sym);
            let doc = super::SearchDoc {
                name: sym.name.clone(),
                kind: sym.kind_label(),
                file: entry.path.to_string(),
                line: sym.selection_start() + 1,
                signature: sym.detail.clone(),
                doc: sym.documentation.clone(),
                tokens: tokens.clone(),
                generated,
            };
            names.push((sym.name.clone(), sym.kind_label()));
            let id = tfidf.docs.len();
            tfidf.docs.push(doc);
            tfidf.add(id, &tokens);
        }
    }
    tfidf.finalize();
    (tfidf, names)
}

/// Rebuild the index with only the docs that pass `parsed`'s filters —
/// run_search filters at build time, so scoring happens inside the narrowed
/// set (codegraph: filters narrow, FTS scores within).
fn filtered_index(tfidf: &TfIdfIndex, parsed: &super::ParsedQuery) -> TfIdfIndex {
    let mut out = TfIdfIndex::new();
    for doc in &tfidf.docs {
        if !doc_passes_filters(doc, parsed, language_from_path(&doc.file)) {
            continue;
        }
        let tokens = doc.tokens.clone();
        let id = out.docs.len();
        out.docs.push(doc.clone());
        out.add(id, &tokens);
    }
    out.finalize();
    out
}

/// Query the way `run_search` does: filters parsed out, remaining text
/// expanded (stem + identifier segments at original casing), scored.
fn corpus_query(tfidf: &TfIdfIndex, raw: &str, limit: usize) -> Vec<super::SearchResult> {
    let parsed = parse_query(raw);
    let tfidf = filtered_index(tfidf, &parsed);
    let query_tokens: Vec<String> = super::tokenize_query(&parsed.text)
        .into_iter()
        .map(|t| super::stem(&t))
        .collect();
    let mut all_query_tokens = query_tokens.clone();
    for qt in &query_tokens {
        for s in super::tokenize_identifier(qt) {
            if !all_query_tokens.contains(&s) {
                all_query_tokens.push(s);
            }
        }
    }
    for seg in super::query_segments(&parsed.text) {
        if !all_query_tokens.contains(&seg) {
            all_query_tokens.push(seg);
        }
    }
    if all_query_tokens.is_empty() {
        // Filters-only query: return everything that passes, ordered by name
        // (same as run_search).
        let mut docs: Vec<&super::SearchDoc> = tfidf.docs.iter().collect();
        docs.sort_by(|a, b| {
            a.name
                .cmp(&b.name)
                .then_with(|| a.generated.cmp(&b.generated))
        });
        docs.truncate(limit);
        return docs
            .into_iter()
            .map(|d| super::SearchResult {
                name: d.name.clone(),
                kind: d.kind.clone(),
                file: d.file.clone(),
                line: d.line,
                signature: d.signature.clone(),
                doc: d.doc.clone(),
                generated: d.generated,
                score: 1.0,
            })
            .collect();
    }
    tfidf.search(&all_query_tokens, limit)
}

// ── battery ─────────────────────────────────────────────────────────────────

#[test]
fn corpus_parses_clean() {
    // P3 guard: no phantom errors on any corpus file.
    for entry in corpus() {
        let data = parse_by_extension(entry.path, entry.src);
        assert!(
            data.syntax_errors.is_empty(),
            "{}: {:?}",
            entry.path,
            data.syntax_errors
        );
    }
}

#[test]
fn battery_acronym_names_top_hit() {
    let (tfidf, _) = build_corpus_index();
    // P1: acronym-run names match when typed as-is.
    let r = corpus_query(&tfidf, "HTMLParser", 3);
    assert_eq!(r.first().map(|x| x.name.as_str()), Some("HTMLParser"));
    let r = corpus_query(&tfidf, "JSONParser", 3);
    assert_eq!(r.first().map(|x| x.name.as_str()), Some("JSONParser"));
    // Digits glue: querying the words still finds the encoder.
    let r = corpus_query(&tfidf, "base64 encode", 3);
    assert_eq!(r.first().map(|x| x.name.as_str()), Some("Base64Encoder"));
}

#[test]
fn battery_semantic_and_kdoc() {
    let (tfidf, _) = build_corpus_index();
    // Signature/name match on a real Okio-style method. writeUtf8 must be in
    // the top 3 — readUtf8 can match via its glued class-header doc.
    let r = corpus_query(&tfidf, "writeUtf8", 3);
    assert!(
        r.iter().any(|x| x.name == "writeUtf8"),
        "writeUtf8 must rank high: {r:?}"
    );
    // KDoc prose finds the class (documentation tokens are indexed).
    let r = corpus_query(&tfidf, "buffered source", 5);
    assert!(
        r.iter().any(|x| x.name == "Buffer"),
        "KDoc prose must find Buffer: {r:?}"
    );
    // Same-name method: writeUtf8 must be in the top 3 (readUtf8 can match
    // via its glued class-header doc).
    let r = corpus_query(&tfidf, "writeUtf8", 3);
    assert!(
        r.iter().any(|x| x.name == "writeUtf8"),
        "writeUtf8 must rank high: {r:?}"
    );
}

#[test]
fn battery_kind_filter() {
    let (tfidf, _) = build_corpus_index();
    // P2: kind:class narrows to classes; Builder's methods are excluded.
    let r = corpus_query(&tfidf, "kind:class", 20);
    assert!(!r.is_empty());
    assert!(r.iter().all(|x| x.kind == "class"), "got: {:?}", r);
}

#[test]
fn battery_path_and_name_filters() {
    let (tfidf, _) = build_corpus_index();
    // P2: path + name filters compose (case-insensitive).
    let r = corpus_query(&tfidf, "kind:class path:codec", 5);
    assert_eq!(r.first().map(|x| x.name.as_str()), Some("Base64Encoder"));
    let r = corpus_query(&tfidf, "kind:method name:parse", 10);
    assert_eq!(r.len(), 3); // parse x2 + parseFrom (substring match)
    assert!(r.iter().all(|x| x.name.contains("parse")));
}

#[test]
fn battery_generated_downranks_on_tie() {
    let (tfidf, _) = build_corpus_index();
    // P4: same-name Request — real implementation ranks above the protobuf stub.
    // Note: `fun build(): Request` legitimately ranks first on the return-type
    // token — the P4 contract is about same-name ordering, not overall rank.
    let r = corpus_query(&tfidf, "Request", 10);
    let reqs: Vec<_> = r.iter().filter(|x| x.name == "Request").collect();
    assert_eq!(reqs.len(), 2, "both Request classes must match: {r:?}");
    assert!(!reqs[0].generated, "real Request must rank first: {r:?}");
    assert!(reqs[1].generated, "generated stub must rank second: {r:?}");
}

#[test]
fn battery_filters_apply_before_scoring() {
    let (tfidf, _) = build_corpus_index();
    // P2: filters narrow the candidate set; free text scores within it.
    // Both Request classes match "Request", but kind:method excludes classes.
    let r = corpus_query(&tfidf, "kind:method Request", 10);
    assert!(!r.is_empty());
    assert!(r.iter().all(|x| x.kind == "method"));
    // The proto stub's parseFrom is still findable by name+path.
    let r = corpus_query(&tfidf, "kind:method path:proto parseFrom", 5);
    assert_eq!(r.first().map(|x| x.name.as_str()), Some("parseFrom"));
    assert!(r[0].generated);
}

#[test]
fn corpus_symbols_sanity() {
    // Guard the corpus itself: known symbol count so accidental corpus edits
    // (which would silently weaken/strengthen the battery) are noticed.
    let (_, names) = build_corpus_index();
    let classes = names.iter().filter(|(_, k)| k == "class").count();
    let methods = names.iter().filter(|(_, k)| k == "method").count();
    assert_eq!(classes, 8, "corpus class count drifted: {names:?}");
    assert_eq!(methods, 10, "corpus method count drifted: {names:?}");
}
