//! Tests for generated-file detection (`src/indexer/generated.rs`).

use crate::indexer::generated::{detect_generated, has_generated_header, is_generated_path};

// ── path signal ─────────────────────────────────────────────────────────────

#[test]
fn generated_path_protobuf_and_grpc() {
    assert!(is_generated_path("src/main/proto/User.pb.kt"));
    assert!(is_generated_path("src/common/grpc/UserServiceGrpc.kt"));
    assert!(is_generated_path("proto/UserGrpc.kt"));
    assert!(is_generated_path("api/UserOuterClass.java"));
    assert!(is_generated_path("api/UserServiceGrpc.java"));
}

#[test]
fn generated_path_kapt_mock_generic() {
    assert!(is_generated_path("buildSrc/Thing.generated.kt"));
    assert!(is_generated_path("test/MockRepository_mock.kt"));
    assert!(is_generated_path("generated/Config.gen.kt"));
    assert!(is_generated_path("kapt/DataBindingComponent.g.java"));
}

#[test]
fn generated_path_case_insensitive() {
    assert!(is_generated_path("api/UserOUTERCLASS.JAVA"));
    assert!(is_generated_path("proto/User.PB.KT"));
}

#[test]
fn generated_path_hand_written_not_matched() {
    assert!(!is_generated_path("src/Main.kt"));
    assert!(!is_generated_path("src/GrpcClient.kt")); // plain name, no suffix
    assert!(!is_generated_path("src/OuterClassParser.kt"));
    assert!(!is_generated_path("src/my_mocks_fixture.kt")); // not a suffix match
}

// ── content signal ──────────────────────────────────────────────────────────

#[test]
fn generated_header_protoc_banner() {
    let src = "// Code generated by the protocol buffer compiler. DO NOT EDIT!\n\
               // source: user.proto\n\
               package com.example";
    assert!(has_generated_header(src));
}

#[test]
fn generated_header_kapt_banner() {
    let src = "// AUTO-GENERATED FILE. DO NOT MODIFY.\n\
               // Generated by kapt.\n\
               package com.example";
    assert!(has_generated_header(src));
}

#[test]
fn generated_header_after_license_preamble() {
    // Banner below a license block still counts (within the 60-line head).
    let src = "/*\n * Copyright 2024 …\n * Licensed under the Apache License …\n */\n\
               // This file was generated by Dagger.\n\
               package com.example";
    assert!(has_generated_header(src));
}

#[test]
fn generated_header_hand_written_not_matched() {
    // Prose mentioning "generated" is not a banner.
    assert!(!has_generated_header(
        "// the table below is generated at runtime\npackage x"
    ));
    // A string constant in the body is not a banner (not a comment).
    assert!(!has_generated_header(
        "class Gen {\n  val s = \"// Code generated by X. DO NOT EDIT.\"\n}"
    ));
    // No comment leader → ignored.
    assert!(!has_generated_header(
        "Code generated by X. DO NOT EDIT!\npackage x"
    ));
}

#[test]
fn generated_header_empty_or_short() {
    assert!(!has_generated_header(""));
    assert!(!has_generated_header("package com.example\nclass A"));
}

// ── union signal ────────────────────────────────────────────────────────────

#[test]
fn detect_generated_union() {
    // Path signal alone.
    assert!(detect_generated("proto/User.pb.kt", "package x"));
    // Content signal alone (hand-written-looking name).
    assert!(detect_generated(
        "src/Payroll.kt",
        "// Code generated by inhouse. DO NOT EDIT.\npackage x"
    ));
    // Neither.
    assert!(!detect_generated("src/Main.kt", "package x\nclass Main"));
}
