//! Generated-file detection — path convention OR content banner.
//!
//! Mirrors codegraph's `generated-detection.ts` (MIT) with the same two
//! deliberately separate signals, combined once at index time and persisted
//! on `FileData.generated` so ranking never re-reads file headers per query:
//!
//! 1. [`is_generated_path`] — PATH only, pure and synchronous; safe to call
//!    anywhere including in a sort comparator.
//! 2. [`has_generated_header`] — CONTENT banner in the file's head, evaluated
//!    once at index time (the content is already in memory for parsing).
//!
//! The verdict is a **relevance hint, not a hard filter** (codegraph #1500
//! lesson): generated nodes stay fully reachable, they just rank below a real
//! implementation with the same name. `build/` and `Generated/` directories
//! are already excluded at scan time (`EXCLUDED_DIR_NAMES`); these patterns
//! cover generated files that are committed into the source tree itself.

/// Lowercased filename suffixes for tool-generated Kotlin/Java files that are
/// commonly committed into the source tree (protobuf, gRPC, kapt/Lombok,
/// mocks). Precision-first: a false positive silently demotes hand-written
/// code in every ranking path.
const GENERATED_SUFFIXES: &[&str] = &[
    // protobuf / gRPC (protoc-gen-kotlin, protoc-gen-grpc-kotlin, wire)
    ".pb.kt",
    "_pb.kt",
    "_grpc.kt",
    "_grpc_pb.kt",
    // protoc-gen-grpc-kotlin emits `*ServiceGrpc.kt` (no underscore); same
    // convention as protoc-gen-grpc-java's `*Grpc.java` below.
    "grpc.kt",
    // generic generated marker (`.generated.kt` / `.gen.kt`)
    ".generated.kt",
    ".gen.kt",
    // mockgen-style mocks committed for tests
    "_mock.kt",
    "_mocks.kt",
    // protoc-gen-java emits `*OuterClass.java`; protoc-gen-grpc-java `*Grpc.java`
    "outerclass.java",
    "grpc.java",
    // kapt / Lombok style single-dot generation
    ".g.java",
];

/// Whether `path` looks like a tool-generated source file based on its
/// filename (lowercased suffix match). Path-only, no content read.
pub(crate) fn is_generated_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    GENERATED_SUFFIXES.iter().any(|s| lower.ends_with(s))
}

/// How much of a file's head to consider "the header": generous enough for a
/// build-tag block + license preamble above the banner, tight enough that a
/// `"// Code generated …"` string constant in the *body* of a generator's own
/// source cannot masquerade as a banner.
const HEADER_SCAN_CHARS: usize = 8192;
const HEADER_SCAN_LINES: usize = 60;

/// Banners recognized at the head of a file. Each is a real convention
/// emitted by a widely-used Kotlin/Java generator (protoc, kapt, Dagger,
/// kotlinx-serialization plugin, Android codegen). Precision-first.
fn has_generated_banner(line: &str) -> bool {
    let l = line.to_lowercase();
    // protoc / protobuf: "Code generated by the protocol buffer compiler. DO NOT EDIT!"
    if l.contains("code generated") && l.contains("do not edit") {
        return true;
    }
    // Common Kotlin/Java: "AUTO-GENERATED FILE. DO NOT MODIFY." / "Generated by X. DO NOT EDIT."
    if (l.contains("auto-generated") || l.contains("autogenerated") || l.contains("generated by"))
        && (l.contains("do not edit") || l.contains("do not modify") || l.contains("do not change"))
    {
        return true;
    }
    // "This file was generated by …" (kapt / Xcode-style)
    if l.contains("this file was generated") || l.contains("this file is generated") {
        return true;
    }
    false
}

/// Whether the head of `content` carries a recognized machine-generation
/// banner. Bounded to [`HEADER_SCAN_CHARS`] / [`HEADER_SCAN_LINES`], with a
/// cheap "generat" fast-reject before any line splitting so hand-written
/// files cost ~nothing. The banner must sit on a line-comment line (`//` or
/// `/*` leaders); string literals and prose that merely contain the words are
/// not flagged.
pub(crate) fn has_generated_header(content: &str) -> bool {
    // Byte-slice at a char boundary: an 8 KiB cap can otherwise land inside a
    // multi-byte char (e.g. CJK in large Swift files) and panic — the user
    // hit this on a full rebuild in 0.32.0 (exit 134).
    let head = &content[..content.floor_char_boundary(content.len().min(HEADER_SCAN_CHARS))];
    if !head.to_lowercase().contains("generat") {
        return false;
    }
    for line in head.lines().take(HEADER_SCAN_LINES) {
        let trimmed = line.trim_start();
        let is_comment =
            trimmed.starts_with("//") || trimmed.starts_with("/*") || trimmed.starts_with('*');
        if !is_comment {
            continue;
        }
        if has_generated_banner(trimmed) {
            return true;
        }
    }
    false
}

/// The union signal: path convention OR content banner. This is what the
/// indexer persists to `FileData.generated`.
pub(crate) fn detect_generated(path: &str, content: &str) -> bool {
    is_generated_path(path) || has_generated_header(content)
}
